version: '3.7'

services:     
  redis-master:
    image: redis:6-alpine
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    networks:
      - redis_network
 
  redis-slave:
    image: redis:6-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - ./data:/data
    networks:
      - redis_network
     
  # Instance 1
  redis-sentinel:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    networks:
      - redis_network
 
  # Instance 2
  redis-sentinel2:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    networks:
      - redis_network
 
  # Instance 3
  redis-sentinel3:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    networks:
      - redis_network

  networks:
    default:
      external:
        name: redis_network
